YSKProje.ToDo.Web/Areas/Admin/Controllers/AciliyetController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YskProje.Todo.DTO.DTOs.AciliyetDto;
using YSKProje.ToDo.Business.Interfaces;
using YSKProje.ToDo.Entities.Concrete;


namespace YSKProje.ToDo.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class AciliyetController : Controller
    {
       private readonly IAciliyetService _aciliyetService;
        private readonly IMapper _mapper;
        public AciliyetController(IAciliyetService aciliyetService, IMapper mapper)
        {
         _aciliyetService = aciliyetService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            TempData["Active"] = "aciliyet";  
            return View(_mapper.Map<List<AciliyetListDto>>(_aciliyetService.GetirHepsi()));
        }
        public IActionResult EkleAciliyet()
        {
            TempData["Active"] = "aciliyet";
            return View(new AciliyetAddDto());
        }
        [HttpPost]
        public IActionResult EkleAciliyet(AciliyetAddDto model)
        {
            TempData["Active"] = "aciliyet";
            if (ModelState.IsValid)
            {
                _aciliyetService.Kaydet(new Aciliyet()
                {
                    Tanim = model.Tanim
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult GuncelleAciliyet(int id)
        {
            TempData["Active"] = "aciliyet";
            return View(_mapper.Map<AciliyetUpdateDto>(_aciliyetService.GetirIdile(id)));
        }
        [HttpPost]
        public IActionResult GuncelleAciliyet(AciliyetUpdateDto model)
        {
            TempData["Active"] = "aciliyet";
            if (ModelState.IsValid)
            {
            _aciliyetService.Guncelle(new Aciliyet
            {
                Id = model.Id,
                Tanim = model.Tanim
            });
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

YSKProje.ToDo.Web/Areas/Admin/Views/Aciliyet/EkleAciliyet.cshtml
@model AciliyetAddDto
@{
    ViewData["Title"] = "EkleAciliyet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form  class="w-75 mx-auto p-3" method="post">
    <div class="form-group">
        <label asp-for="Tanim">Tanım </label>
        <span asp-validation-for="Tanim" class="text-danger"></span>
        <input asp-for="Tanim" type="text" class="form-control" />
    </div>

    <button type="submit" class="btn btn-info btn-sm"><i class="fas fa-check"></i> Kaydet</button>
</form>
@section JavaScript{

    <script src="~/lib/jqueryValidate/jquery.validate.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

YSKProje.ToDo.Web/Areas/Admin/Views/Aciliyet/GuncelleAciliyet.cshtml
@model AciliyetUpdateDto
@{
    ViewData["Title"] = "GuncelleAciliyet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-action="GuncelleAciliyet" class="w-75 mx-auto p-3" method="post">
    <input type="hidden"asp-for="Id"/>
    <div class="form-group">
        <label asp-for="Tanim">Tanım </label>
        <span asp-validation-for="Tanim" class="text-danger"></span>
        <input asp-for="Tanim" type="text" class="form-control" />
    </div>
    <button type="submit" class="btn btn-info btn-sm"><i class="fas fa-check"></i> Güncelle</button>
</form>
@section JavaScript{

    <script src="~/lib/jqueryValidate/jquery.validate.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

YSKProje.ToDo.Web/Areas/Admin/Views/Aciliyet/Index.cshtml
@model List<AciliyetListDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@if (Model.Count != 0)
{
    <a asp-action="EkleAciliyet" asp-controller="Aciliyet" class="btn btn-sm btn-outline-dark my-2"><i class="fas fa-plus-circle"></i> Aciliyet Ekle</a>
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th>Tanım</th>
                <th>İşlem</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Tanim</td>
                    <td>
                        <a asp-action="GuncelleAciliyet" asp-controller="Aciliyet" asp-route-id="@item.Id" class="btn btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center lead mt-4">
        <p class="lead">
        Sistemde Kayıtlı Aciliyet Durumu Bulunamadı 
        </p>
        <a asp-action="EkleAciliyet" asp-controller="Aciliyet" class="btn btn-sm btn-outline-dark my-2"><i class="fas fa-plus-circle"></i> Aciliyet Ekle</a>

    </div>
}