YSKProje.ToDo.Web/Areas/Admin/Controllers/GorevController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YskProje.Todo.DTO.DTOs.GorevDto;
using YSKProje.ToDo.Business.Interfaces;
using YSKProje.ToDo.Entities.Concrete;
using YSKProje.ToDo.Web.Controllers;

namespace YSKProje.ToDo.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class GorevController : Controller
    {

        private readonly IGorevService _gorevService;
        private readonly IAciliyetService _aciliyetService;
        private readonly IUrunService _urunService;
        private readonly IMapper _mapper;
        public GorevController(IGorevService gorevService, IAciliyetService aciliyetService, IUrunService urunService, IMapper mapper)
        {
            _mapper = mapper;
            _gorevService = gorevService;
            _aciliyetService = aciliyetService;
            _urunService = urunService;
        }
        public IActionResult Index()
        {
            
            return View(_mapper.Map<List<GorevListDto>>(_gorevService.GetirAciliyetIleTamamlanmayan()));

        }

        public IActionResult EkleGorev()
        {

            ViewBag.Aciliyetler = new SelectList(_aciliyetService.GetirHepsi(), "Id", "Tanim");
            ViewBag.Urun = new SelectList(_urunService.GetirHepsi(), "Id", "UrunAdi");
            TempData["Active"] = "gorev";
            return View(new GorevAddDto());
        }
        [HttpPost]
        public IActionResult EkleGorev(GorevAddDto model)
        {
            TempData["Active"] = "gorev";
            if (ModelState.IsValid)
            {
                _gorevService.Kaydet(new Gorev()
                {
                    Aciklama = model.Aciklama,
                    Ad = model.Ad,
                    AciliyetId = model.AciliyetId,
                    UrunId=model.UrunId
                });
                return RedirectToAction("Index");
            }
            ViewBag.Aciliyetler = new SelectList(_aciliyetService.GetirHepsi(), "Id", "Tanim");
            ViewBag.Urun = new SelectList(_urunService.GetirHepsi(), "Id", "UrunAdi");
            return View(model);

        }
        public IActionResult GuncelleGorev(int id)
        {
            TempData["Active"] = "gorev";
            var gorev = _gorevService.GetirIdile(id);
            ViewBag.Aciliyetler = new SelectList(_aciliyetService.GetirHepsi(), "Id", "Tanim", gorev.AciliyetId);
            ViewBag.Urun = new SelectList(_urunService.GetirHepsi(), "Id", "UrunAdi");
            return View(_mapper.Map<GorevUpdateDto>(_gorevService.GetirIdile(id)));
        }

        [HttpPost]
        public IActionResult GuncelleGorev(GorevUpdateDto model)
        {
            TempData["Active"] = "gorev";
            if (ModelState.IsValid)
            {
                _gorevService.Guncelle(new Gorev
                {
                    Id = model.Id,
                    Ad = model.Ad,
                    Aciklama = model.Aciklama,
                    AciliyetId = model.AciliyetId,
                });
              
              
                return RedirectToAction("Index");
            }
            ViewBag.Aciliyetler = new SelectList(_aciliyetService.GetirHepsi(), "Id", "Tanim", model.AciliyetId);
            ViewBag.Urun = new SelectList(_urunService.GetirHepsi(), "Id", "UrunAdi");
            return View(model);
        }
        public IActionResult SilGorev(int id )
        {
            _gorevService.Sil(new Gorev { Id = id });
            return Json(null);
        }
    }

}

YSKProje.ToDo.Web/Areas/Admin/Controllers/IsEmriController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YskProje.Todo.DTO.DTOs.AppUserDto;
using YskProje.Todo.DTO.DTOs.GorevDto;
using YskProje.Todo.DTO.DTOs.PersonelDto;
using YSKProje.ToDo.Business.Interfaces;
using YSKProje.ToDo.Entities.Concrete;
using YSKProje.ToDo.Web.Controllers;

namespace YSKProje.ToDo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class IsEmriController : BaseIdentityController
    {
        private readonly IAppUserService _appUserService;
        private readonly IGorevService _gorevService;
        private readonly IDosyaService _dosyaService;
        private readonly IMapper _mapper;
        public IsEmriController(IAppUserService appUserService, IGorevService gorevService, UserManager<AppUser> userManager, IDosyaService dosyaService, IMapper mapper):base(userManager)
        {
            _appUserService = appUserService;
            _gorevService = gorevService;
            _dosyaService = dosyaService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            TempData["Active"] = "isemri";
      
            return View(_mapper.Map<List<GorevAllListDto>>(_gorevService.GetirTumTablolar()));
        }
        public IActionResult AtaPersonel(int id, string s, int sayfa = 1)
        {
            TempData["Active"] = "isemri";

            ViewBag.AktifSayfa = sayfa;

            ViewBag.Aranan = s;

            var personeller = _mapper.Map<List<AppUserListDto>>(_appUserService.GetirAdminOlmayanlar(out int toplamSayfa, s, sayfa));
            ViewBag.ToplamSayfa = toplamSayfa;

            ViewBag.Personeller = personeller;

            return View(_mapper.Map<GorevListDto>(_gorevService.GetirAciliyetId(id)));
        }
        [HttpPost]
        public IActionResult AtaPersonel(PersonelGorevlendirDto model)
        {
            var guncellenecekgorev = _gorevService.GetirIdile(model.GorevId);
            guncellenecekgorev.AppUserId = model.PersonelId;
            _gorevService.Guncelle(guncellenecekgorev);
            return RedirectToAction("Index");
        }
        public IActionResult GorevlendirPersonel(PersonelGorevlendirDto model)
        {

            TempData["Active"] = "isemri";

            PersonelGorevlendirListDto personelGorevlendirModel = new PersonelGorevlendirListDto
            {
                AppUser = _mapper.Map<AppUserListDto>(_userManager.Users.FirstOrDefault(I => I.Id == model.PersonelId)),
                Gorev = _mapper.Map<GorevListDto>(_gorevService.GetirAciliyetId(model.GorevId))
            };
            return View(personelGorevlendirModel);
        }
        public IActionResult Detaylandir(int id)
        {
            TempData["Active"] = "isemri";
            return View(_mapper.Map<GorevAllListDto>(_gorevService.GetirRaporlarIdIle(id)));
          
        }
           public IActionResult GetirExcel(int id)
        {
            return File(_dosyaService.AktarExcel(_gorevService.GetirRaporlarIdIle(id).Raporlar), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Guid.NewGuid() + ".xlsx");
        }

        public IActionResult GetirPdf(int id)
        {
            var path = _dosyaService.AktarPdf(_gorevService.GetirRaporlarIdIle(id).Raporlar);
            return File(path, "application/pdf", Guid.NewGuid() + ".pdf");
        }
    }
}

YSKProje.ToDo.Web/Areas/Admin/Controllers/ProfilController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YskProje.Todo.DTO.DTOs.AppUserDto;
using YSKProje.ToDo.Entities.Concrete;
using YSKProje.ToDo.Web.Controllers;

namespace YSKProje.ToDo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProfilController : BaseIdentityController
    {
    
        private readonly IMapper _mapper;
        public ProfilController(UserManager<AppUser> userManager,IMapper mapper):base(userManager)
        {
           
            _mapper = mapper;
        }
        public async Task< IActionResult> Index()
        {
            TempData["Active"] = "profil";
            return View(_mapper.Map<AppUserListDto>(await GirisYapanKullanici()));
        }
        [HttpPost]
        public async Task<IActionResult> Index(AppUserListDto model)
        {
            if (ModelState.IsValid)
            {
                var guncelenecekKullanici = _userManager.Users.FirstOrDefault(x => x.Id == model.Id);
                guncelenecekKullanici.Name = model.Name;
                guncelenecekKullanici.Surname = model.SurName;
                guncelenecekKullanici.Email = model.Email;
                await _userManager.UpdateAsync(guncelenecekKullanici);
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

YSKProje.ToDo.Web/Areas/Admin/Controllers/UrunController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YskProje.Todo.DTO.DTOs.UrunDto;
using YSKProje.ToDo.Business.Interfaces;
using YSKProje.ToDo.Entities.Concrete;

namespace YSKProje.ToDo.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UrunController : Controller
    {
        private readonly IUrunService _urunService;
        private readonly IMapper _mapper;
        public UrunController(IUrunService urunService, IMapper mapper)
        {
            _urunService = urunService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            TempData["Active"] = "urunler";
            return View(_mapper.Map<List<UrunListDto>>(_urunService.GetirHepsi()));
        }
        public IActionResult EkleUrun()
        {
            TempData["Active"] = "urunler";
            return View(new UrunAddDto());
        }
        [HttpPost]
        public IActionResult EkleUrun(UrunAddDto model)
        {
            TempData["Active"] = "urunler";
            if (ModelState.IsValid)
            {
                _urunService.Kaydet(new Urun()
                {
                    UrunAdi = model.UrunAdi,
                    UrunAciklama = model.UrunAciklama,
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult GuncelleUrun(int id)
        {
            TempData["Active"] = "urunler";
            return View(_mapper.Map<UrunUpdateDto>(_urunService.GetirIdile(id)));
        }
        [HttpPost]
        public IActionResult GuncelleUrun(UrunUpdateDto model)
        {
            TempData["Active"] = "urunler";
            if (ModelState.IsValid)
            {
                _urunService.Guncelle(new Urun
                {
                    Id = model.Id,
                    UrunAdi = model.UrunAdi,
                    UrunAciklama = model.UrunAciklama
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

YSKProje.ToDo.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{ 
    string active = string.Empty;
    if (TempData["Active"]!=null)
    {
        active = TempData["Active"].ToString();
    }
    //string active2 = TempData["Active"]?.ToString();
}

<!DOCTYPE html>
<html lang="tr">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/lib/bootswatch/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/lib/template-css/simple-sidebar.css" rel="stylesheet" />
    <link href="~/lib/fontAwesome/css/all.min.css" rel="stylesheet" />
</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border border-primary border-left-0 border-top-0 border border-bottom-0 border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Admin Layout</div>
            <div class="list-group list-group-flush">
                <a asp-action="Index" asp-controller="Gorev" class="list-group-item list-group-item-action  @(active=="gorev"?"active":"")"><i class="fas fa-tasks"></i>  Görev İşlemleri</a>
                <a asp-action="Index" asp-controller="Urun" class="list-group-item list-group-item-action  @(active=="urun"?"active":"")"><i class="fas fa-tasks"></i>  Ürün İşlemleri</a>
                <a asp-action="Index" asp-controller="Aciliyet" class="list-group-item list-group-item-action @(active=="aciliyet"?"active":"") "><i class="fas fa-exclamation"></i> Aciliyet İşlemleri</a>
                <a asp-action="Index" asp-controller="IsEmri" class="list-group-item list-group-item-action  @(active=="isemri"?"active":"") "> <i class="fas fa-file"></i> İş Emri </a>
                <a  class="list-group-item list-group-item-action  @(active=="profil"?"active":"") "><i class="fas fa-chart-pie"></i> Grafikler</a>
                <a href="#" class="list-group-item list-group-item-action "><i class="fas fa-chart-area"></i> İstatistikler</a>
                <a href="#" class="list-group-item list-group-item-action "><i class="fas fa-bell"></i> Bildirimlerim</a>
                <a asp-action="Index"asp-controller="Profil" class="list-group-item list-group-item-action "><i class="fas fa-user"></i> Profilim</a>
                <a asp-area="" asp-action="CikisYap"asp-controller="Home" class="list-group-item list-group-item-action "><i class="fas fa-sign-out-alt"></i> Çıkış Yap</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle"><i class="fas fa-exchange-alt"></i> Menü</button>

                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </div>*@
            </nav>

            <div class="container-fluid">
                <script src="~/lib/fontAwesome/js/all.min.js"></script>
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("JavaScript",false)
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

</body>

</html>